---
- name: Soapbox Backend Configure
  hosts: all
  gather_facts: true
  vars:
    asdf_user: pleroma
    asdf_group: pleroma

  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "erlang"
      versions: ["24.3.4.2"]
      global: "24.3.4.2"
    - name: "elixir"
      versions: ["1.13"]
      global: "1.13"

  tasks:
  - name: Setup ASDF
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/asdf.sh'

  - name: Setup ASDF completion
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/completions/asdf.bash'

  - name: Install Hex
    become: yes
    become_user: pleroma
    shell: bash -ilc 'mix local.hex --force'
    changed_when: >
      "Will always run, don't show that it changed" == 1
    args:
      chdir: /opt/pleroma

  - name: Install Rebar
    become: yes
    become_user: pleroma
    shell: bash -ilc 'mix local.rebar --force'
    changed_when: >
      "Will always run, don't show that it changed" == 1
    args:
      chdir: /opt/pleroma

  - name: Get Deps
    become: yes
    become_user: pleroma
    shell: bash -ilc 'mix deps.get'
    changed_when: >
      "Will always run, don't show that it changed" == 1
    args:
      chdir: /opt/pleroma

  - name: Compile Rebased
    become: yes
    become_user: pleroma
    shell: bash -ilc 'MIX_ENV=prod mix compile'
    changed_when: >
      "Will always run, don't show that it changed" == 1
    args:
      chdir: /opt/pleroma

  - name: Copy Soapbox Service config
    copy:
      src: /opt/pleroma/installation/pleroma.service
      dest: /etc/systemd/system/pleroma.service
      mode: preserve
      remote_src: yes
